[project]
name = "adeptly-mcp-sdk"
version = "0.1.0"
description = "Internal SDK for Adeptly agents (contracts, governance, MCP wiring)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["mcp-agent @ git+https://github.com/lastmile-ai/mcp-agent.git@main"]
